DEBUG_MODE = False
SET_SEED = 15
# 4

CHANCE_OF_ALL_ROOM_OBJ_COND = 0.6
CHANCE_OF_ALL_ROOM_WALL_COND = 0.7

MAX_ROOM_OBJ_COMBINATIONS = 1_000_000
MAX_ROOM_WALL_COMBINATIONS = 800_000
MAX_UPPER_FLOOR_ROOM_COMBINATIONS = 300_000
MAX_UPPER_FLOOR_PLAYER_COMBINATIONS = 100_000
# MAX_HOUSE_COMBINATIONS = 1_000

USED_LANGUAGE = "german"

SHOW_PRINTS = False
"""
Can be german or english
"""